/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author abdularifin
 */
public class ViewEditService extends javax.swing.JPanel {

    /**
     * Creates new form ViewService
     */
    public ViewEditService() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addServicePanel = new javax.swing.JPanel();
        leftPanel = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        titleLbl = new javax.swing.JLabel();
        servicePanel = new javax.swing.JPanel();
        serviceLbl = new javax.swing.JLabel();
        serviceForm = new javax.swing.JTextField();
        beratPanel = new javax.swing.JPanel();
        beratLbl = new javax.swing.JLabel();
        beratForm = new javax.swing.JComboBox<>();
        sPremiumPanel = new javax.swing.JPanel();
        sPremiumLbl = new javax.swing.JLabel();
        sPremiumForm = new javax.swing.JCheckBox();
        hargaSpremiumLbl = new javax.swing.JLabel();
        hargaSpremiumForm = new javax.swing.JTextField();
        premiumPanel = new javax.swing.JPanel();
        premiumLbl = new javax.swing.JLabel();
        premiumForm = new javax.swing.JCheckBox();
        premiumHargaLbl = new javax.swing.JLabel();
        premiumHargaForm = new javax.swing.JTextField();
        standartPanel = new javax.swing.JPanel();
        standartLbl = new javax.swing.JLabel();
        standartForm = new javax.swing.JCheckBox();
        standartHargaLbl = new javax.swing.JLabel();
        standartHargaForm = new javax.swing.JTextField();
        btnApply = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        rightPanel = new javax.swing.JPanel();
        iconRight = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        addServicePanel.setBackground(new java.awt.Color(204, 255, 255));

        leftPanel.setBackground(new java.awt.Color(255, 255, 255));
        leftPanel.setPreferredSize(new java.awt.Dimension(512, 96));

        Header.setBackground(new java.awt.Color(255, 255, 255));

        titleLbl.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        titleLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laundrykasir/img/Edit.png"))); // NOI18N
        titleLbl.setText("Edit Service");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
            .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HeaderLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(titleLbl)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
            .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HeaderLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(titleLbl)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        servicePanel.setBackground(new java.awt.Color(255, 255, 255));

        serviceLbl.setText("Service");

        serviceForm.setText("Service");

        javax.swing.GroupLayout servicePanelLayout = new javax.swing.GroupLayout(servicePanel);
        servicePanel.setLayout(servicePanelLayout);
        servicePanelLayout.setHorizontalGroup(
            servicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(servicePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(servicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(serviceLbl)
                    .addComponent(serviceForm, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(198, Short.MAX_VALUE))
        );
        servicePanelLayout.setVerticalGroup(
            servicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(servicePanelLayout.createSequentialGroup()
                .addComponent(serviceLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(serviceForm, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        beratPanel.setBackground(new java.awt.Color(255, 255, 255));

        beratLbl.setText("Berat");

        beratForm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout beratPanelLayout = new javax.swing.GroupLayout(beratPanel);
        beratPanel.setLayout(beratPanelLayout);
        beratPanelLayout.setHorizontalGroup(
            beratPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(beratPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(beratPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(beratLbl)
                    .addComponent(beratForm, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        beratPanelLayout.setVerticalGroup(
            beratPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(beratPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(beratLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(beratForm, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        sPremiumPanel.setBackground(new java.awt.Color(255, 255, 255));

        sPremiumLbl.setText("Paket");

        sPremiumForm.setText("Super Premium");
        sPremiumForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sPremiumFormActionPerformed(evt);
            }
        });

        hargaSpremiumLbl.setText("Harga");

        hargaSpremiumForm.setText("0");

        javax.swing.GroupLayout sPremiumPanelLayout = new javax.swing.GroupLayout(sPremiumPanel);
        sPremiumPanel.setLayout(sPremiumPanelLayout);
        sPremiumPanelLayout.setHorizontalGroup(
            sPremiumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sPremiumPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sPremiumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sPremiumLbl)
                    .addComponent(sPremiumForm))
                .addGap(124, 124, 124)
                .addGroup(sPremiumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hargaSpremiumLbl)
                    .addComponent(hargaSpremiumForm, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        sPremiumPanelLayout.setVerticalGroup(
            sPremiumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sPremiumPanelLayout.createSequentialGroup()
                .addGroup(sPremiumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sPremiumLbl)
                    .addComponent(hargaSpremiumLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sPremiumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sPremiumForm)
                    .addComponent(hargaSpremiumForm, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        premiumPanel.setBackground(new java.awt.Color(255, 255, 255));

        premiumLbl.setText("Paket");

        premiumForm.setText("Premium");
        premiumForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                premiumFormActionPerformed(evt);
            }
        });

        premiumHargaLbl.setText("Harga");

        premiumHargaForm.setText("0");

        javax.swing.GroupLayout premiumPanelLayout = new javax.swing.GroupLayout(premiumPanel);
        premiumPanel.setLayout(premiumPanelLayout);
        premiumPanelLayout.setHorizontalGroup(
            premiumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(premiumPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(premiumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(premiumLbl)
                    .addComponent(premiumForm))
                .addGap(162, 162, 162)
                .addGroup(premiumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(premiumHargaLbl)
                    .addComponent(premiumHargaForm, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        premiumPanelLayout.setVerticalGroup(
            premiumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(premiumPanelLayout.createSequentialGroup()
                .addGroup(premiumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(premiumHargaLbl)
                    .addComponent(premiumLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(premiumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(premiumForm)
                    .addComponent(premiumHargaForm, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        standartPanel.setBackground(new java.awt.Color(255, 255, 255));

        standartLbl.setText("Paket");

        standartForm.setText("Standart");
        standartForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                standartFormActionPerformed(evt);
            }
        });

        standartHargaLbl.setText("Harga");

        standartHargaForm.setText("0");
        standartHargaForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                standartHargaFormActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout standartPanelLayout = new javax.swing.GroupLayout(standartPanel);
        standartPanel.setLayout(standartPanelLayout);
        standartPanelLayout.setHorizontalGroup(
            standartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(standartPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(standartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(standartLbl)
                    .addComponent(standartForm))
                .addGap(162, 162, 162)
                .addGroup(standartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(standartHargaLbl)
                    .addComponent(standartHargaForm, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        standartPanelLayout.setVerticalGroup(
            standartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(standartPanelLayout.createSequentialGroup()
                .addGroup(standartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(standartHargaLbl)
                    .addComponent(standartLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(standartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(standartForm)
                    .addComponent(standartHargaForm, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnApply.setBackground(new java.awt.Color(102, 204, 255));
        btnApply.setText("Apply");

        btnCancel.setBackground(new java.awt.Color(255, 51, 51));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sPremiumPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(premiumPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(standartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(beratPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(servicePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnApply, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)))
                .addGap(12, 12, 12))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(servicePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(beratPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sPremiumPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(premiumPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(standartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApply, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        rightPanel.setBackground(new java.awt.Color(255, 255, 255));

        iconRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laundrykasir/img/Washing machine loads the laundry into itself.png"))); // NOI18N

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconRight, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(iconRight)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout addServicePanelLayout = new javax.swing.GroupLayout(addServicePanel);
        addServicePanel.setLayout(addServicePanelLayout);
        addServicePanelLayout.setHorizontalGroup(
            addServicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addServicePanelLayout.createSequentialGroup()
                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addServicePanelLayout.setVerticalGroup(
            addServicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
            .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(addServicePanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void sPremiumFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sPremiumFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sPremiumFormActionPerformed

    private void premiumFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_premiumFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_premiumFormActionPerformed

    private void standartFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_standartFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_standartFormActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    private void standartHargaFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_standartHargaFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_standartHargaFormActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JPanel addServicePanel;
    private javax.swing.JComboBox<String> beratForm;
    private javax.swing.JLabel beratLbl;
    private javax.swing.JPanel beratPanel;
    private javax.swing.JButton btnApply;
    private javax.swing.JButton btnCancel;
    private javax.swing.JTextField hargaSpremiumForm;
    private javax.swing.JLabel hargaSpremiumLbl;
    private javax.swing.JLabel iconRight;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JCheckBox premiumForm;
    private javax.swing.JTextField premiumHargaForm;
    private javax.swing.JLabel premiumHargaLbl;
    private javax.swing.JLabel premiumLbl;
    private javax.swing.JPanel premiumPanel;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JCheckBox sPremiumForm;
    private javax.swing.JLabel sPremiumLbl;
    private javax.swing.JPanel sPremiumPanel;
    private javax.swing.JTextField serviceForm;
    private javax.swing.JLabel serviceLbl;
    private javax.swing.JPanel servicePanel;
    private javax.swing.JCheckBox standartForm;
    private javax.swing.JTextField standartHargaForm;
    private javax.swing.JLabel standartHargaLbl;
    private javax.swing.JLabel standartLbl;
    private javax.swing.JPanel standartPanel;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
